
CREATE TABLE Donos (
	IDDono INTEGER NOT NULL
	, Tipo CHAR(2) NOT NULL
	, Nome VARCHAR(80) NOT NULL
	, RazaoSocial VARCHAR(80) NULL
	, CPF CHAR(11) NULL
	, CNPJ CHAR(14) NULL
	, Email VARCHAR(60) NOT NULL
	, DataNascimento DATE NOT NULL
	, PRIMARY KEY(IDDono)
);

CREATE TABLE Funcionarios (
	IDFuncionario INTEGER NOT NULL
	, Nome VARCHAR(80) NOT NULL
	, CPF CHAR(11) NOT NULL
	, Email VARCHAR(60) NOT NULL
	, DataNascimento DATE NOT NULL
	, PRIMARY KEY(IDFuncionario)
);

CREATE TABLE Servicos (
	IDServico INTEGER NOT NULL
	, NomeServico VARCHAR(100) NOT NULL
	, Descricao VARCHAR(500) NOT NULL
	, Preco NUMERIC NOT NULL
	, PRIMARY KEY(IDServico)
	
);

CREATE TABLE Animais (
	IDAnimal INTEGER NOT NULL
	, IDDono INTEGER NOT NULL
	, Nome VARCHAR(30) NOT NULL
	, Especie VARCHAR(30) NOT NULL
	, Raca VARCHAR(50) NOT NULL
	, Idade VARCHAR(2) NOT NULL
	, Sexo CHAR(1) NOT NULL
	, PRIMARY KEY(IDAnimal)
	, FOREIGN KEY(IDDono) REFERENCES Donos
);

CREATE TABLE Consultas (
	IDConsulta INTEGER NOT NULL
	, IDAnimal INTEGER NOT NULL
	, IDServico INTEGER NOT NULL
	, DataConsulta DATE NOT NULL
	, HoraConsulta TIME NOT NULL
	, MotivoConsulta VARCHAR(500) NOT NULL
	, Diagnostico VARCHAR(500) NULL
	, Tratamento VARCHAR(500) NULL
	, PRIMARY KEY(IDConsulta)
	, FOREIGN KEY(IDAnimal) REFERENCES Animais
	, FOREIGN KEY(IDServico) REFERENCES Servicos
);


